<?php
/**
 * @file
 * Install file for the RedHen Raiser Customization module.
 */

/**
 * Implements hook_install().
 */
function redhen_raiser_custom_config_install() {
  variable_set('site_name', 'Capital Area Food Bank of DC');
  variable_set('site_slogan', 'Together We Can Solve Hunger™');
  variable_set('site_frontpage', 'node/1');
  variable_set('theme_default', 'cafb_dc');

  redhen_raiser_custom_default_nodes();
}
/**
 * Install default content.
 */
function redhen_raiser_custom_default_nodes() {
  // Load helper functions.
  include_once 'sites/all/libraries/ts_install_helpers/ts_install_helpers.php';
  include_once 'sites/all/modules/custom/dc_campaign_development/includes/cafb_dc_install.content.inc';

  // Basic pages and menus.
  $stubbed_nodes = cafb_dc_stubbed_nodes();
  $node_menu_items = ts_install_helpers_create_content($stubbed_nodes);
  ts_install_helpers_create_menu_items($node_menu_items);
}

/**
 * Set the new default theme to cafb_dc rather than raiser.
 */
function redhen_raiser_custom_config_update_7000(&$sandbox) {
  variable_set('theme_default', 'cafb_dc');
}
